# Generated by Django 6.0.6 on 2026-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='plan',
            field=models.CharField(default='monthly', max_length=20),
        ),
    ]
